package apply.aaron.wirebarley.configuration

import apply.aaron.wirebarley.client.currenylayer.EnableCurrentLayerClients
import org.springframework.boot.autoconfigure.EnableAutoConfiguration
import org.springframework.context.annotation.Configuration
import org.springframework.scheduling.annotation.EnableScheduling

@EnableAutoConfiguration
@Configuration
@EnableScheduling
@EnableCurrentLayerClients
class WireBarleyApplySpringConfiguration
